services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: always

  mysql:
    image: mysql:5.7
    container_name: guac-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_root_password
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: some_password
    volumes:
      - guac-mysql:/var/lib/mysql

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: some_password
      GUACAMOLE_HOME: /guac-home
      TOTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - guac-home:/guac-home

volumes:
  guac-mysql:
  guac-home: