{
 "title": "CVE Vulns Scanner",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "NOMBRE TOTAL DE VULNERABILITE DANS LE PARC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total FROM vulns;\r\n"
    }
   ]
  },
  {
   "title": "NOMBRE DE CVE UNIQUE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT cve) AS total_unique FROM vulns;\r\n"
    }
   ]
  },
  {
   "title": "VULNERABILITE LES PLUS GRAVES",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT cve, MAX(cvss) AS max_cvss, COUNT(*) AS occurences\r\nFROM vulns\r\nGROUP BY cve\r\nORDER BY max_cvss DESC\r\n\r\n"
    }
   ]
  },
  {
   "title": "HOTE DES VULNERABILITE LES PLUS GRAVE",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ip, port, service, product, version, cve, cvss\r\nFROM vulns\r\nWHERE cvss >= 9.0\r\nORDER BY cvss DESC;\r\n"
    }
   ]
  },
  {
   "title": "TOUTES LES VULNERABILITE PRESENTE",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT cve, COUNT(*) AS occurrences\r\nFROM vulns\r\nWHERE cve IS NOT NULL\r\nGROUP BY cve\r\nORDER BY occurrences DESC;\r\n"
    }
   ]
  },
  {
   "title": "VULNERABILITE PAR HOTE",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  ip,\r\n  service,\r\n  product,\r\n  version,\r\n  cve,\r\n  MAX(cvss) AS severity,\r\n  MAX(url) AS reference\r\nFROM vulns\r\nWHERE cve IS NOT NULL\r\nGROUP BY ip, service, product, version, cve\r\nORDER BY severity DESC;\r\n"
    }
   ]
  }
 ]
}